# Generated by Django 4.1.1 on 2022-10-24 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_transaction_id_mycourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name=uuid.UUID('b33f1b65-7432-4198-9dce-036a9b62a78f')),
        ),
    ]
