# Generated by Django 4.1.1 on 2022-11-22 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name=uuid.UUID('2acb19f5-4306-41e8-bfec-e0ae641c906c')),
        ),
    ]
