# Generated by Django 4.1.1 on 2022-11-24 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name=uuid.UUID('76b3eb0c-0c53-4b71-ae89-5f07029698f8')),
        ),
    ]
