# Generated by Django 4.1.1 on 2022-10-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.studentclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_theme', to='courses.theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_theme', to='courses.subject'),
        ),
    ]
