# Generated by Django 4.1.1 on 2022-11-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursevideo_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='price',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='student_class',
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='price',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
