# Generated by Django 4.1.1 on 2022-11-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_subject_price_remove_theme_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='description_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='description_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='description_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='description_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name_az',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name_be',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name_en',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name_kk',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name_ky',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name_ru',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name_tg',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name_uz',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='name_zh',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='studentage',
            name='age_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentage',
            name='age_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentage',
            name='age_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentage',
            name='age_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentage',
            name='age_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentage',
            name='age_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentage',
            name='age_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentage',
            name='age_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentage',
            name='age_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_be',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_tg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='name_zh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_az',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_be',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_kk',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ky',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_tg',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_zh',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_be',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_kk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_ky',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_tg',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_uz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_zh',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
